"""Initial baseline

Revision ID: 303b9c407579
Revises: 
Create Date: 2026-05-06 14:40:04.907794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303b9c407579'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('maintenance_message', sa.Text(), nullable=False),
    sa.Column('notification_banner_active', sa.Boolean(), nullable=False),
    sa.Column('notification_banner_message', sa.String(length=500), nullable=False),
    sa.Column('notification_banner_type', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index('idx_ambulance_request_requested_at', 'ambulance_requests', ['requested_at'], unique=False)
    op.create_index('idx_ambulance_request_status', 'ambulance_requests', ['status'], unique=False)
    op.create_index('idx_user_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_is_verified', 'users', ['is_verified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_is_verified', table_name='users')
    op.drop_index('idx_user_is_active', table_name='users')
    op.drop_index('idx_ambulance_request_status', table_name='ambulance_requests')
    op.drop_index('idx_ambulance_request_requested_at', table_name='ambulance_requests')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
