#!/bin/bash
# Vercel Deployment Script for ALERA

echo "🚀 ALERA Healthcare Deployment to Vercel"
echo "=========================================="
echo ""
echo "📋 Pre-Deployment Checklist:"
echo "✅ Build: Production build successful"
echo "✅ Code Quality: TypeScript & ESLint passing"
echo "✅ Repository: Committed to GitHub (emmanueldrah/alera-typescript)"
echo "✅ Configuration: vercel.json configured"
echo ""
echo "🌐 Deployment Steps:"
echo ""
echo "Option 1: Using Vercel Dashboard (Easiest)"
echo "─────────────────────────────────────────"
echo "1. Go to https://vercel.com"
echo "2. Click 'New Project'"
echo "3. Import GitHub repository: emmanueldrah/alera-typescript"
echo "4. Vercel auto-detects Vite + Node.js configuration"
echo "5. Click 'Deploy'"
echo "6. Your app will be live in ~2 minutes!"
echo ""
echo "Option 2: Using Vercel CLI"
echo "───────────────────────────"
echo "Run: npx vercel --prod"
echo ""
echo "This will:"
echo "• Connect your GitHub account (first time)"
echo "• Link your project to Vercel"
echo "• Deploy your code"
echo "• Give you a live URL"
echo ""
echo "Option 3: Automatic Git Push Deploy"
echo "────────────────────────────────────"
echo "If you've connected Vercel to GitHub:"
echo "1. Make changes to your code"
echo "2. Push to GitHub: git push origin main"
echo "3. Vercel auto-deploys automatically!"
echo ""
echo "=========================================="
echo "📊 Expected Deployment Result:"
echo ""
echo "URL: https://alera-[your-vercel-domain].vercel.app"
echo "Deployment Time: ~2-5 minutes"
echo "Build Command: npm run build"
echo "Output Directory: dist"
echo ""
echo "🎉 Your ALERA app will be live and accessible worldwide!"
echo ""
